version: '3.3'
services:
  pybase:
    build:
      context: ./pybase
    image: "${img}/pybase"
  dockver:
    build:
      context: ./flask_app
      cache_from:
        - ${img}/pybase:latest"
      args:
        Img: "${img}/pybase" 
        Docker_GID: ${Docker_GID}
    image: ${img}_dockver:${tag}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5080:5000
    restart: always
