version: '3.3'
services:
  pybase:
    build:
      context: ./pybase
    image: ${img}:${tag}
  dockver:
    build:
      context: ./flask_app
      args:
        Img: ${img}:${tag} 
        Docker_GID: ${Docker_GID}
    image: ${img}_dockver:${tag}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 5080:5000
    restart: always
